--- #YAML:1.0
name:               Dancer-Plugin-Feed
version:            0.4
abstract:           easy to generate feed rss or atom for Dancer applications.
author:
    - Natal Ngétal <hobbestigrou@erakis.im>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Dancer:      1.2001
    Test::More:  0
    XML::Feed:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
